# Generated by Django 4.1.7 on 2023-02-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='starting_date',
            new_name='created_at',
        ),
    ]
