# Generated by Django 4.1.7 on 2023-02-25 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_group_total_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0003_rename_starting_date_subscription_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
