# Generated by Django 4.1.7 on 2023-02-23 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('about', models.TextField(null=True)),
                ('icon', models.FileField(null=True, upload_to='')),
                ('timeline_img', models.FileField(null=True, upload_to='')),
                ('intro_video', models.FileField(null=True, upload_to='')),
                ('subscription_rate', models.PositiveIntegerField(null=True)),
                ('total_member', models.PositiveBigIntegerField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.SET, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
