# Generated by Django 4.1.7 on 2023-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_launched',
            field=models.BooleanField(default=False),
        ),
    ]
