# Generated by Django 4.1.7 on 2023-02-23 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_group_created_at_alter_group_about_alter_group_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
