# Generated by Django 4.1.7 on 2023-02-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='total_member',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
