# Generated by Django 4.1.7 on 2023-02-23 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('bio', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('timeline_pic', models.TextField(blank=True, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=20, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.SET, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
